# Generated by Django 5.0.1 on 2024-01-24 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Maxsulot kategoriyasi')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30, verbose_name='Ism')),
                ('l_name', models.CharField(max_length=30, verbose_name='Familiya')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yoshi')),
                ('product', models.CharField(max_length=50, verbose_name='Maxsulotlar')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Maxsulot nomi')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Ishlab chiqarilgan vaqti')),
                ('delete_day', models.IntegerField(verbose_name='Yaroqlilik muddati')),
                ('price', models.IntegerField(verbose_name='Narhi')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.category', verbose_name='Category')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.item')),
            ],
        ),
    ]
