# Generated by Django 5.0.1 on 2024-01-24 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Maxsulot narxi')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Karta hisobi')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.customer', verbose_name='Customer Id')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.product')),
            ],
        ),
    ]
