# Generated by Django 5.0.1 on 2024-01-24 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_shopcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='product',
        ),
    ]
