# Generated by Django 5.0.1 on 2024-01-26 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_alter_purchasehistory_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descriptions', models.TextField(verbose_name='Maxsulot haqida')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.RenameModel(
            old_name='Shopcard',
            new_name='Shopcart',
        ),
        migrations.RemoveField(
            model_name='product',
            name='item_id',
        ),
        migrations.RenameField(
            model_name='shopcart',
            old_name='customer_id',
            new_name='customer_name',
        ),
        migrations.AddField(
            model_name='admin',
            name='status',
            field=models.CharField(choices=[('admin', 'Admin'), ('creater', 'Creater')], default='admin', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='product',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopapp.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin',
            name='name',
            field=models.CharField(default=1, max_length=30, verbose_name='Ismi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='items_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopapp.items', verbose_name='Items'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
